# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Cloudflare Tunnel add-on
version: "1.1.0"
slug: cf_tunnel
description: Cloudflare Tunnel add-on
url: "https://github.com/home-assistant/addons-example/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
auth_api: true
host_network: true
hassio_api: true
hassio_role: admin
map:
  - config:rw
options:
  cf_certificate: "/config/cloudflare/cert.pem"
  cf_tunnel_name: "homeassistant"
  cf_domain: null
  cf_subdomain: null
schema:
  cf_certificate: "str"
  cf_tunnel_name: "str"
  cf_domain: "str"
  cf_subdomain: "str"
# image: "ghcr.io/home-assistant/{arch}-addon-example"
